export const DEMOCRATIC = 'democratic';
export const COMP_AUTH = 'competitively-authoritarian';
export const FULL_AUTH = 'fully-authoritarian';

export const getCategory = (feature) => {
  if (isDemocratic(feature)) return DEMOCRATIC;
  if (isCompAuth(feature)) return COMP_AUTH;
  if (isFullAuth(feature)) return FULL_AUTH;
  return;
};

export const getColor = (feature) => {
  if (isDemocratic(feature)) return 'none';
  if (isCompAuth(feature)) return '#F6911E';
  if (isFullAuth(feature)) return '#E80689';
  return 'white';
}

export const isDemocratic = (feature) => {
  return data.democratic.findIndex((country) => {
    return feature.properties.name_long.includes(country) ||
      country.includes(feature.properties.name_long);
  }) !== -1;
};

export const isCompAuth = (feature) => {
  return data.competitiveAuthoritarian.findIndex((country) => {
    return feature.properties.name_long.includes(country) ||
      country.includes(feature.properties.name_long);
  }) !== -1;
};

export const isFullAuth = (feature) => {
  return data.fullyAuthoritarian.findIndex((country) => {
    return feature.properties.name_long.includes(country) ||
      country.includes(feature.properties.name_long);
  }) !== -1;
};

export const getDemocratic = (features) => {
  return features.filter(feature => {
    return isDemocratic(feature);
  });
};

export const getNonDemocratic = (features) => {
  return features.filter(feature => {
    return isFullAuth(feature) || isCompAuth(feature);
  });
};

export const papers = {
  Tajikstan: [{
    title: 'Repression and Persecution Under Tajikistan’s Authoritarian Regime',
    link: 'https://hrf.org/press_posts/repression-and-persecution-under-tajikistans-authoritarian-regime/',
  }],
  Morocco: [{
    title: 'LGBT Community Under Increasing Pressure in Morocco',
    link: 'https://hrf.org/press_posts/lgbt-community-under-increasing-pressure-in-morocco/',
  }],
  Burundi: [{
    title: 'Burundi Elections Proceed Despite Coronavirus Outbreak',
    link: 'https://hrf.org/press_posts/burundi-elections-proceed-despite-coronavirus-outbreak/',
  }],
  Egypt: [{
    title: 'Remembering Shady Habash: A Victim of Egypt’s Horrific Prison Conditions',
    link: 'https://hrf.org/press_posts/remembering-shady-habash-a-victim-of-egypts-horrific-prison-conditions/',
  }, {
    link: 'https://hrf.org/press_posts/the-state-of-protest-russia-egypt-bolivia-iraq-guinea-and-iran/',
    title:  'The State of Protest: Russia, Egypt, Bolivia, Iraq, Guinea, and Iran',
  }],
  Cuba: [{
    link: 'https://hrf.org/press_posts/cuba-60-years-of-revolution-60-years-of-oppression/',
    title: 'Cuba: 60 Years of Revolution, 60 Years of Oppression'
  }],
  Vietnam: [{
    link: 'https://hrf.org/press_posts/vietnams-covid-success-belies-escalating-crackdown-on-rights/',
    title: 'Vietnam’s COVID Success Belies Escalating Crackdown on Rights',
  }],
  'Honk Kong': [{
    link: 'https://hrf.org/press_posts/hong-kong-government-targets-pro-democracy-activists-amid-covid-19/',
    title: 'Hong Kong Government Targets Pro-Democracy Activists Amid COVID-19',
  }, {
    link: 'https://hrf.org/press_posts/hong-kongs-national-security-law-the-nail-in-the-coffin-for-one-country-two-systems/',
    title: 'Hong Kong’s National Security Law: The Nail in the Coffin for One Country, Two Systems'
  }, {
    link: 'https://hrf.org/press_posts/the-state-of-protest-sudan-venezuela-zimbabwe-nicaragua-algeria-and-hong-kong/',
    title:  'The State of Protest: Sudan, Venezuela, Zimbabwe, Nicaragua, Algeria, and Hong Kong',
  }],
  Sudan: [{
    link: 'https://hrf.org/press_posts/the-state-of-protest-sudan-venezuela-zimbabwe-nicaragua-algeria-and-hong-kong/',
    title:  'The State of Protest: Sudan, Venezuela, Zimbabwe, Nicaragua, Algeria, and Hong Kong',
  }],
  Venezuela: [{
    link: 'https://hrf.org/press_posts/the-state-of-protest-sudan-venezuela-zimbabwe-nicaragua-algeria-and-hong-kong/',
    title:  'The State of Protest: Sudan, Venezuela, Zimbabwe, Nicaragua, Algeria, and Hong Kong',
  }],
  Zimbabwe: [{
    link: 'https://hrf.org/press_posts/the-state-of-protest-sudan-venezuela-zimbabwe-nicaragua-algeria-and-hong-kong/',
    title:  'The State of Protest: Sudan, Venezuela, Zimbabwe, Nicaragua, Algeria, and Hong Kong',
  }],
  Nicaragua: [{
    link: 'https://hrf.org/press_posts/the-state-of-protest-sudan-venezuela-zimbabwe-nicaragua-algeria-and-hong-kong/',
    title:  'The State of Protest: Sudan, Venezuela, Zimbabwe, Nicaragua, Algeria, and Hong Kong',
  }],
  Algeria: [{
    link: 'https://hrf.org/press_posts/the-state-of-protest-sudan-venezuela-zimbabwe-nicaragua-algeria-and-hong-kong/',
    title:  'The State of Protest: Sudan, Venezuela, Zimbabwe, Nicaragua, Algeria, and Hong Kong',
  }],
  Russia: [{
    link: 'https://hrf.org/press_posts/the-state-of-protest-russia-egypt-bolivia-iraq-guinea-and-iran/',
    title:  'The State of Protest: Russia, Egypt, Bolivia, Iraq, Guinea, and Iran',
  }],
  Iran: [{
    link: 'https://hrf.org/press_posts/the-state-of-protest-russia-egypt-bolivia-iraq-guinea-and-iran/',
    title:  'The State of Protest: Russia, Egypt, Bolivia, Iraq, Guinea, and Iran',
  }],
  Iraq: [{
    link: 'https://hrf.org/press_posts/the-state-of-protest-russia-egypt-bolivia-iraq-guinea-and-iran/',
    title:  'The State of Protest: Russia, Egypt, Bolivia, Iraq, Guinea, and Iran',
  }],
  Bolivia: [{
    link: 'https://hrf.org/press_posts/the-state-of-protest-russia-egypt-bolivia-iraq-guinea-and-iran/',
    title:  'The State of Protest: Russia, Egypt, Bolivia, Iraq, Guinea, and Iran',
  }],
  Guinea: [{
    link: 'https://hrf.org/press_posts/the-state-of-protest-russia-egypt-bolivia-iraq-guinea-and-iran/',
    title:  'The State of Protest: Russia, Egypt, Bolivia, Iraq, Guinea, and Iran',
  }],
}

export const data = {
	democratic: [
    'Antigua and Barbuda', 'Argentina', 'Bahamas', 'Barbados', 'Belize', 'Brazil', 'Canada', 'Chile', 'Colombia', 'Costa Rica', 'Dominica', 'Dominican Republic', 'El Salvador', 'Haiti', 'French Guiana', 'Grenada', 'Guatemala', 'Guyana',
    'Jamaica', 'Mexico', 'Panama', 'Paraguay', 'Peru', 'Puerto Rico', 'St. Kitts and Nevis', 'St. Lucia', 'St. Vincent and Grenadines', 'Suriname', 'Trinidad and Tobago', 'United States of America', 'Uruguay', 'Israel', 'Lebanon', 'Ukraine', 'Georgia', 'Benin', 'Botswana',
    'Cape Verde', 'Ghana', 'Lesotho', 'Liberia', 'Mali', 'Mauritius', 'Namibia', 'Senegal', 'Sao Tome and Principe', 'South Africa', 'Australia', 'Bhutan', 'East Timor (or Timor-Leste)', 'India', 'Indonesia', 'Japan', 'Kiribati', 'Marshall Islands', 'Micronesia', 'Mongolia',
    'Nauru', 'New Zealand', 'Palau', 'Papua New Guinea', 'Samoa', 'Solomon Islands', 'South Korea', 'Republic of Korea', 'Taiwan', 'Tonga', 'Tuvalu', 'Vanuatu', 'Albania', 'Andorra', 'Austria', 'Belgium', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia',
    'Czech Republic', 'Cyprus', 'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Iceland', 'Ireland', 'Italy', 'Latvia', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Malta', 'Macedonia', 'Monaco', 'Netherlands',
    'Norway', 'Poland', 'Portugal', 'Romania', 'San Marino', 'Serbia', 'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland', 'United Kingdom', 'Greenland',
  ],
  competitiveAuthoritarian: [
    'Bolivia', 'Nicaragua', 'Ecuador', 'Honduras', 'Tunisia', 'Armenia', 'Kyrgyzstan', 'Moldova', 'Burkina Faso', 'Central African Republic', 'Comoros', 'Côte D’Ivoire', 'Côte d\'Ivoire', 'Gambia', 'Guinea', 'Guinea-Bissau', 'Kenya', 'Madagascar', 'Malawi',
    'Mauritania', 'Mozambique', 'Niger', 'Nigeria', 'Seychelles', 'Sierra Leone', 'Tanzania', 'Togo', 'Zambia', 'Zanzibar', 'Bangladesh', 'Fiji', 'Malaysia', 'Maldives', 'Myanmar/Burma', 'Nepal', 'Pakistan', 'Sri Lanka', 'Hong Kong', 'Philippines', 'Macau', 'Hungary', 'Kosovo', 'Montenegro',
  ],
  fullyAuthoritarian: [
    'Cuba', 'Venezuela', 'Algeria', 'Bahrain', 'Egypt', 'Iran', 'Iraq', 'Jordan', 'Kuwait', 'Libya', 'Morocco', 'Oman', 'Palestine', 'Qatar', 'Saudi Arabia',
    'Turkey', 'Syria', 'United Arab Emirates', 'Western Sahara', 'Yemen', 'Azerbaijan', 'Belarus', 'Kazakhstan', 'Russia', 'Tajikistan', 'Turkmenistan', 'Uzbekistan', 'Angola', 'Burundi', 'Cameroon', 'Chad',
    'Democratic Republic of Congo-(Kinshasa)', 'Democratic Republic of the Congo', 'Djibouti', 'Equatorial Guinea', 'Ethiopia', 'Eritrea', 'Eswatini (Swaziland)', 'Gabon', 'Republic of Congo (Brazzaville)', 'Rwanda', 'Somalia', 'Sudan', 'South Sudan', 'Uganda', 'Zimbabwe', 'Afghanistan', 'Brunei', 'Cambodia',
    'China', 'Laos', 'Lao PDR', 'North Korea', 'Dem. Rep. Korea', 'Singapore', 'Thailand', 'Vietnam',
  ],
};

const speakerNames = [
  'Esther Htusan',
  'Audrey Mbugua',
  'Thae Yong-Ho',
  'Yeonmi Park',
  'Park Sang Hak',
  'Molly McKew',
  'Denise Ho',
  'Netiwit Chotiphatphaisal',
  'Lisa Sánchez',
  'Rosa María Payá',
  'Danilo “El Sexto” Maldonado',
  'Kimberley Motley',
  'William Dobson',
  'Hannah Song',
  'Nico Sell',
  'Maryam Faghihimani',
  'Marina Nemat',
  'Marcel Granier',
  'Abeer Allam',
  'Wael Ghonim',
  'Jean-Robert Cadet',
  'Ahmed Benchemsi',
  'Kasha Jacqueline (Nabagesera)',
  'Srdja Popovic',
  'Chen Guangcheng',
  'Ti-Anna Wang',
  'Abdalaziz Alhamza',
  'Tutu Alicante',
  'Yulia Marushevska',
];

export const speakers = {
  Burma: ['Esther Htusan'],
  Kenya: ['Audrey Mbugua'],
  'North Korea': ['Thae Yong-Ho', 'Yeonmi Park', 'Park Sang Hak'],
  Georgia: ['Molly McKew'],
  'Honk Kong': ['Denise Ho'],
  Thailand: ['Netiwit Chotiphatphaisal'],
  Mexico: ['Lisa Sánchez'],
  Cuba: ['Rosa María Payá', 'Danilo “El Sexto” Maldonado'],
  USA: ['Kimberley Motley', 'William Dobson', 'Hannah Song', 'Nico Sell'],
  Iran: ['Maryam Faghihimani', 'Marina Nemat'],
  Venezuela: ['Marcel Granier'],
  Egypt: ['Abeer Allam', 'Wael Ghonim'],
  Haiti: ['Jean-Robert Cadet'],
  Morocco: ['Ahmed Benchemsi'],
  Uganda: ['Kasha Jacqueline (Nabagesera)'],
  Serbia: ['Srdja Popovic'],
  China: ['Chen Guangcheng', 'Ti-Anna Wang'],
  Syria: ['Abdalaziz Alhamza'],
  'Equatorial Guinea': ['Tutu Alicante'],
  Ukraine: ['Yulia Marushevska'],
}

export const names = [
  { 'Fartuun Adan': ["Somalia"], link: 'https://hrf.org/events_talks/nothing-left-to-fear-the-struggle-for-a-new-somalia/' },
  { 'Mai Khoi': ["Taiwan","Vietnam"], link: 'https://hrf.org/events_talks/an-artists-call-for-vietnams-freedom/' },
  { 'Aayat Alqormozi': ["Taiwan","Bahrain"], link: 'https://hrf.org/events_talks/peace-can-be-scary/' },
  { 'Myeong Seong-hee': ["Taiwan","China","North Korea"], link: 'https://hrf.org/events_talks/performance-myeong-seong-hee/' },
  { 'Ji Seong-ho': ["South Korea","North Korea"], link: 'https://hrf.org/events_talks/from-famine-to-freedom-a-north-koreans-story-of-escape/' },
  { 'Clare Rewcastle Brown': ["Taiwan","Malaysia"], link: 'https://hrf.org/events_talks/malaysia-a-story-of-hope/' },
  { 'Bill Tai': ["Taiwan"], link: 'https://hrf.org/events_talks/blockchain-virtual-nations/' },
  { 'Mariana Dahan': ["Taiwan"], link: 'https://hrf.org/events_talks/ending-human-trafficking-how-technology-can-save-lives/' },
  { 'undefined': ["Taiwan","Ethiopia","Eritrea"], link: 'https://hrf.org/events_talks/why-we-need-to-speak-up-for-eritrea/' },
  { 'Mu Sochua': ["Taiwan","Cambodia"], link: 'https://hrf.org/events_talks/fighting-dictatorship-in-cambodia/' },
  { 'Megha Rajagopalan': ["Taiwan","China"], link: 'https://hrf.org/events_talks/inside-chinas-digital-authoritarianism/' },
  { 'undefined': ["Taiwan","Russia"], link: 'https://hrf.org/events_talks/standing-up-for-freedom-in-russia/' },
  { 'Omar Sharif Jr.': ["Taiwan","Egypt"], link: 'https://hrf.org/events_talks/from-egypt-to-taiwan-shared-hopes-for-lgbtq-equality/' },
  { 'Joanna Hausmann': ["Venezuela"], link: 'https://hrf.org/events_talks/comedic-performance-2/' },
  { 'Fang Zheng': ["China"], link: 'https://hrf.org/events_talks/why-china-wants-the-world-to-forget-the-tiananmen-massacre/' },
  { 'Rick Doblin': [], link: 'https://hrf.org/events_talks/the-promise-of-psychedelics-for-ptsd/' },
  { 'undefined': ["Togo"], link: 'https://hrf.org/events_talks/how-online-activism-is-bringing-democracy-to-togo/' },
  { 'Fatemah Qaderyan': ["Afghanistan"], link: 'https://hrf.org/events_talks/how-girls-are-using-robotics-to-build-their-futures/' },
  { 'Mai Khoi': ["Vietnam"], link: 'https://hrf.org/events_talks/why-vietnam-silenced-a-pop-star/' },
  { 'Emmanuel Jal': ["Sudan","South Sudan"], link: 'https://hrf.org/events_talks/the-art-of-forgiveness/' },
  { 'Emmanuel Jal': ["Sudan","South Sudan"], link: 'https://hrf.org/events_talks/2018-havel-prize-acceptance-speech-2/' },
  { 'Ian C. Kelly': ["Russia"], link: 'https://hrf.org/events_talks/putins-next-move-a-conversation-with-garry-kasparov-ian-c-kelly/' },
  { 'Yeonmi Park': ["Mongolia","China","North Korea"], link: 'https://hrf.org/events_talks/breaking-the-myth-of-north-korea/' },
  { 'undefined': ["Saudi Arabia"], link: 'https://hrf.org/events_talks/the-false-promise-of-saudi-reform-a-conversation-with-manal-al-sharif/' },
  { 'Arthur Breitman': [], link: 'https://hrf.org/events_talks/blockchain-vs-the-surveillance-state-panel/' },
  { 'Natalia Kaliada': ["Belarus"], link: 'https://hrf.org/events_talks/2018-havel-prize-acceptance-speech/' },
  { 'Tiff Stevenson': [], link: 'https://hrf.org/events_talks/comedic-performance/' },
  { 'Fred Bauma': ["Democratic Republic of the Congo"], link: 'https://hrf.org/events_talks/the-power-of-nonviolence/' },
  { 'undefined': ["Ukraine"], link: 'https://hrf.org/events_talks/the-quest-for-a-better-ukraine/' },
  { 'Ine Eriksen Søreide': ["Norway"], link: 'https://hrf.org/events_talks/welcome-to-norway/' },
  { 'undefined': ["Azerbaijan"], link: 'https://hrf.org/events_talks/my-life-for-democracy/' },
  { 'Rick Doblin': [], link: 'https://hrf.org/events_talks/psychedelics-marijuana-and-healing-ptsd/' },
  { 'Mai Khoi': ["Vietnam"], link: 'https://hrf.org/events_talks/from-stardom-to-the-political-underground/' },
  { 'Meron Estefanos': ["Eritrea"], link: 'https://hrf.org/events_talks/a-conversation-with-thor-halvorssen-on-eritrea/' },
  { 'Mu Sochua': ["Cambodia"], link: 'https://hrf.org/events_talks/my-fight-for-a-free-cambodia/' },
  { 'Ryan Shea': [], link: 'https://hrf.org/events_talks/promoting-freedom-with-decentralized-apps/' },
  { 'Galia Benartzi': [], link: 'https://hrf.org/events_talks/the-evolution-of-money/' },
  { 'Arthur Breitman': [], link: 'https://hrf.org/events_talks/coordinating-people-power/' },
  { 'Jason Silva': [], link: 'https://hrf.org/events_talks/the-future-of-freedom/' },
  { 'Wael Ghonim': ["Egypt"], link: 'https://hrf.org/events_talks/notes-to-my-activist-self/' },
  { 'Jerry Sesanga': ["Uganda"], link: 'https://hrf.org/events_talks/the-orator-of-secrets/' },
  { 'Nasako Besingi': ["Cameroon"], link: 'https://hrf.org/events_talks/freedom-to-protect-the-environment/' },
  { 'undefined': [], link: 'https://hrf.org/events_talks/death-and-the-democratic-deficits-in-dutertes-drug-war/' },
  { 'undefined': ["Eritrea"], link: 'https://hrf.org/events_talks/one-day-seyoum/' },
  { 'undefined': ["Iraq"], link: 'https://hrf.org/events_talks/mosul-eye/' },
  { 'undefined': ["North Korea"], link: 'https://hrf.org/events_talks/in-conversation-with-thor-halvorssen/' },
  { 'Asma Khalifa': ["Libya"], link: 'https://hrf.org/events_talks/what-happened-to-libyas-revolution/' },
  { 'Maziar Bahari': ["Iran"], link: 'https://hrf.org/events_talks/the-liberating-power-of-storytelling/' },
  { 'undefined': ["Nicaragua"], link: 'https://hrf.org/events_talks/unmasking-ortegas-regime/' },
  { 'Fang Zheng': [], link: 'https://hrf.org/events_talks/the-six-four-incident/' },
  { 'Lebo Mashile': ["South Africa"], link: 'https://hrf.org/events_talks/opening-moment/' },
  { 'Clare Rewcastle Brown': ["Malaysia"], link: 'https://hrf.org/events_talks/the-worlds-biggest-financial-scandal/' },
  { 'undefined': ["Thailand"], link: 'https://hrf.org/events_talks/the-student-vs-the-military/' },
  { 'undefined': ["Togo"], link: 'https://hrf.org/events_talks/faure-must-go/' },
  { 'Fatemah Qaderyan': ["Afghanistan"], link: 'https://hrf.org/events_talks/the-afghan-dreamers/' },
  { 'Megha Rajagopalan': ["China"], link: 'https://hrf.org/events_talks/the-police-state-of-the-future-is-already-here/' },
  { 'undefined': ["Yemen"], link: 'https://hrf.org/events_talks/the-women-calling-for-yemens-spring/' },
  { 'Evan Mawarire': ["Zimbabwe"], link: 'https://hrf.org/events_talks/defending-democracy/' },
  { 'Omar Sharif Jr.': ["Egypt"], link: 'https://hrf.org/events_talks/out-of-the-shadows-out-of-the-closet/' },
  { 'undefined': [], link: 'https://hrf.org/events_talks/the-cruel-cut-3/' },
  { 'Memory Banda': ["Malawi"], link: 'https://hrf.org/events_talks/ready-for-change/' },
  { 'Anastasia Lin': ["China"], link: 'https://hrf.org/events_talks/chinas-dark-secret/' },
  { 'undefined': ["Angola"], link: 'https://hrf.org/events_talks/the-killing-fields/' },
  { 'Iyad el-Baghdadi': [], link: 'https://hrf.org/events_talks/it-happened-before-itll-happen-again/' },
  { 'Zineb El Rhazoui': [], link: 'https://hrf.org/events_talks/challenging-power/' },
  { 'undefined': ["Pakistan"], link: 'https://hrf.org/events_talks/hiding-from-the-taliban-in-plain-sight-2/' },
  { 'undefined': ["Russia"], link: 'https://hrf.org/events_talks/russians-are-ready-for-freedom/' },
  { 'Elif Shafak': ["Turkey"], link: 'https://hrf.org/events_talks/in-conversation-with-philippa-thomas-turkey-and-the-loss-of-democracy/' },
  { 'Ji Seong-ho': ["South Korea","North Korea"], link: 'https://hrf.org/events_talks/6000-miles-to-freedom/' },
  { 'Srdja Popovic': ["Serbia","Egypt"], link: 'https://hrf.org/events_talks/in-conversation-with-srdja-popovic-revolution-for-dummies/' },
  { 'Marina Nemat': ["Iran"], link: 'https://hrf.org/events_talks/prisoner-of-tehran/' },
  { 'Wuilly Arteaga': ["Venezuela"], link: 'https://hrf.org/events_talks/the-sound-of-defiance/' },
  { 'undefined': ["Syria"], link: 'https://hrf.org/events_talks/the-white-helmets/' },
  { 'Chris Turner': [], link: 'https://hrf.org/events_talks/performance-comedic-freestyle/' },
  { 'Anas Aremeyaw Anas': ["Ghana"], link: 'https://hrf.org/events_talks/name-shame-and-jail/' },
  { 'Václav Havel': ["Venezuela"], link: 'https://hrf.org/events_talks/2017-havel-prize-acceptance-speech-3/' },
  { 'Václav Havel': ["Bahrain"], link: 'https://hrf.org/events_talks/2017-havel-prize-acceptance-speech-2/' },
  { 'Václav Havel': ["Zimbabwe"], link: 'https://hrf.org/events_talks/2017-havel-prize-acceptance-speech/' },
  { 'Memory Banda': ["Malawi"], link: 'https://hrf.org/events_talks/outlawing-child-marriage/' },
  { 'Joe Lonsdale': [], link: 'https://hrf.org/events_talks/tech-against-corruption/' },
  { 'Wai Wai Nu': [], link: 'https://hrf.org/events_talks/my-struggle-for-burmas-future/' },
  { 'Carah Faye': [], link: 'https://hrf.org/events_talks/performance-freedom-dont-say-a-word/' },
  { 'Grace Jo': ["China","North Korea"], link: 'https://hrf.org/events_talks/my-journey-from-north-korea-to-america/' },
  { 'undefined': ["Russia"], link: 'https://hrf.org/events_talks/why-boris-nemtsov-is-important-for-russia/' },
  { 'Raed Fares': ["Syria"], link: 'https://hrf.org/events_talks/building-a-free-syria-one-town-at-a-time/' },
  { 'Antonietta Ledezma': ["Venezuela"], link: 'https://hrf.org/events_talks/sosvenezuela/' },
  { 'Erna Solberg': ["Norway"], link: 'https://hrf.org/events_talks/keynote-address/' },
  { 'undefined': ["China"], link: 'https://hrf.org/events_talks/a-china-more-just/' },
  { 'Ahmedur Rashid Chowdhury': ["Norway","Bangladesh"], link: 'https://hrf.org/events_talks/who-is-killing-bangladeshs-bloggers/' },
  { 'Mohamed Nasheed': ["Maldives"], link: 'https://hrf.org/events_talks/after-the-coup-in-the-maldives/' },
  { 'undefined': ["Ecuador"], link: 'https://hrf.org/events_talks/caricatura-subversiva/' },
  { 'undefined': ["Somalia"], link: 'https://hrf.org/events_talks/the-cruel-cut/' },
  { 'Anne Applebaum': [], link: 'https://hrf.org/events_talks/saving-democracy-from-disinformation/' },
  { 'undefined': ["Pakistan"], link: 'https://hrf.org/events_talks/hiding-from-the-taliban-in-plain-sight/' },
  { 'Elif Shafak': ["Turkey"], link: 'https://hrf.org/events_talks/turkey-and-the-loss-of-democracy/' },
  { 'Vian Dakhil': ["Iraq"], link: 'https://hrf.org/events_talks/one-yazidi-against-isis/' },
  { 'Firuzeh Mahmoudi': ["Iran"], link: 'https://hrf.org/events_talks/united-for-iran/' },
  { 'Luis Almagro': ["Venezuela"], link: 'https://hrf.org/events_talks/a-new-kind-of-diplomat/' },
  { 'Evan Mawarire': ["Zimbabwe"], link: 'https://hrf.org/events_talks/thisflag/' },
  { 'Thulani Maseko': [], link: 'https://hrf.org/events_talks/using-the-law-to-defeat-a-king/' },
  { 'Denis Mukwege': [], link: 'https://hrf.org/events_talks/stopping-congos-war-on-women/' },
  { 'Aminatou Haidar': ["Western Sahara"], link: 'https://hrf.org/events_talks/whitewashing-western-saharas-struggle-for-freedom/' },
  { 'Emin Milli': ["Azerbaijan"], link: 'https://hrf.org/events_talks/independent-media-is-the-answer/' },
  { 'Anastasia Lin': ["China"], link: 'https://hrf.org/events_talks/my-role-in-acting-for-change/' },
  { 'undefined': ["North Korea"], link: 'https://hrf.org/events_talks/freeing-north-korea-with-flash-drives/' },
  { 'undefined': ["Cuba"], link: 'https://hrf.org/events_talks/orwell-spraypaint-and-the-fight-to-free-cuba/' },
  { 'Wole Soyinka': ["Niger","Nigeria"], link: 'https://hrf.org/events_talks/how-corruption-created-boko-haram/' },
  { 'Vivek Maru': [], link: 'https://hrf.org/events_talks/rule-of-law-for-all/' },
  { 'Lisa Sánchez': ["Mexico"], link: 'https://hrf.org/events_talks/the-drug-laws-that-are-tearing-mexico-apart/' },
  { 'Maajid Nawaz': ["Egypt"], link: 'https://hrf.org/events_talks/the-global-jihadist-insurgency/' },
  { 'Shui-Meng Ng': ["Laos"], link: 'https://hrf.org/events_talks/laos-where-dissidents-disappear/' },
  { 'Roya Mahboob': ["Afghanistan"], link: 'https://hrf.org/events_talks/how-afghan-women-are-coding-for-tomorrow/' },
  { 'Jimmy Wales': [], link: 'https://hrf.org/events_talks/catalysts/' },
  { 'Rachana Sunar': ["Nepal"], link: 'https://hrf.org/events_talks/girls-not-wives/' },
  { 'Anjan Sundaram': ["Rwanda"], link: 'https://hrf.org/events_talks/detecting-a-dictatorship/' },
  { 'Bjørn Ihler': [], link: 'https://hrf.org/events_talks/what-surviving-a-terrorist-attack-taught-me/' },
  { 'Viktor Yushchenko': ["Ukraine","Russia"], link: 'https://hrf.org/events_talks/the-fight-for-a-free-ukraine/' },
  { 'Tom Burgis': ["Niger","Nigeria","Venezuela","Russia"], link: 'https://hrf.org/events_talks/corruption-panel-qa/' },
  { 'Gustavo Coronel': ["Venezuela"], link: 'https://hrf.org/events_talks/corruption-panel-speech-3/' },
  { 'Tom Burgis': [], link: 'https://hrf.org/events_talks/corruption-panel-speech-2/' },
  { 'undefined': ["Russia"], link: 'https://hrf.org/events_talks/corruption-panel-speech/' },
  { 'undefined': ["Russia"], link: 'https://hrf.org/events_talks/russians-are-ready-for-democracy/' },
  { 'undefined': ["Russia"], link: 'https://hrf.org/events_talks/russias-propaganda-war/' },
  { 'Nabeel Rajab': ["Bahrain"], link: 'https://hrf.org/events_talks/letter-from-a-bahraini-prison/' },
  { 'undefined': ["Morocco"], link: 'https://hrf.org/events_talks/african-muslim-and-gay/' },
  { 'undefined': [], link: 'https://hrf.org/events_talks/on-the-way-down-and-cant-take-my-soul/' },
  { 'undefined': [], link: 'https://hrf.org/events_talks/sometimes-i-feel-like-a-motherless-child-and-whoopie/' },
  { 'undefined': ["Mexico"], link: 'https://hrf.org/events_talks/mexicos-rule-of-impunity/' },
  { 'Marc Ona Essangui': ["Gabon"], link: 'https://hrf.org/events_talks/gabons-endangered-activists/' },
  { 'Kambiz Hosseini': ["Iran"], link: 'https://hrf.org/events_talks/can-iran-take-a-joke/' },
  { 'Larry Diamond': [], link: 'https://hrf.org/events_talks/reversing-freedoms-decline/' },
  { 'undefined': ["Tunisia"], link: 'https://hrf.org/events_talks/youth-are-not-the-future/' },
  { 'Václav Havel': ["Norway"], link: 'https://hrf.org/events_talks/a-welcome-to-norway/' },
  { 'Kimberley Motley': ["Afghanistan"], link: 'https://hrf.org/events_talks/rule-of-law-afghanistans-best-hope/' },
  { 'Pravit Rojanaphruk': ["Thailand"], link: 'https://hrf.org/events_talks/freedom-under-thai-military-rule/' },
  { 'Mustafa Akyol': ["Turkey","Russia"], link: 'https://hrf.org/events_talks/turkeys-authoritarian-drift/' },
  { 'Alaa Murabit': ["Libya"], link: 'https://hrf.org/events_talks/arming-women-for-peace-in-libya/' },
  { 'Kenan Malik': ["Mali","India"], link: 'https://hrf.org/events_talks/enemies-of-free-speech/' },
  { 'Shiraz Maher': ["Syria"], link: 'https://hrf.org/events_talks/inside-the-mind-of-an-extremist/' },
  { 'Rayma Suprani': ["Venezuela"], link: 'https://hrf.org/events_talks/drawing-a-line-in-venezuela/' },
  { 'Colin Crowell': [], link: 'https://hrf.org/events_talks/platform-of-possibilities/' },
  { 'Maryam Faghihimani': ["Iran"], link: 'https://hrf.org/events_talks/in-the-house-of-an-ayatollah/' },
  { 'Ji Seong-ho': ["South Korea","North Korea"], link: 'https://hrf.org/events_talks/my-impossible-escape-from-north-korea/' },
  { 'Zineb El Rhazoui': [], link: 'https://hrf.org/events_talks/cartooning-the-prophet/' },
  { 'Saad Mohseni': ["Afghanistan"], link: 'https://hrf.org/events_talks/the-power-of-pop-culture/' },
  { 'Tanele Maseko': ["Norway"], link: 'https://hrf.org/events_talks/greetings-from-cell-g4/' },
  { 'Nico Sell': ["Ghana","Jordan"], link: 'https://hrf.org/events_talks/tyrants-and-technology/' },
  { 'Ian Birrell': ["Sri Lanka"], link: 'https://hrf.org/events_talks/dangerous-words/' },
  { 'Omar Sharif Jr.': ["Egypt"], link: 'https://hrf.org/events_talks/coming-out-in-the-middle-of-a-revolution/' },
  { 'Jamila Raqib': [], link: 'https://hrf.org/events_talks/the-success-of-nonviolent-struggle/' },
  { 'Abdalaziz Alhamza': ["Syria"], link: 'https://hrf.org/events_talks/raqqa-is-being-slaughtered-silently/' },
  { 'undefined': ["China"], link: 'https://hrf.org/events_talks/chinas-information-war/' },
  { 'Janet Hinostroza': ["Ecuador"], link: 'https://hrf.org/events_talks/rise-of-an-elected-autocrat/' },
  { 'Rosa María Payá': ["Cuba"], link: 'https://hrf.org/events_talks/let-cuba-decide/' },
  { 'Fatou Jaw Manneh': ["Gambia"], link: 'https://hrf.org/events_talks/the-gambias-silenced-dissent/' },
  { 'Shorna Shahida Akter': ["Bangladesh"], link: 'https://hrf.org/events_talks/wedding-busters/' },
  { 'Flemming Rose': [], link: 'https://hrf.org/events_talks/free-speech-in-a-globalized-world/' },
  { 'Emily Parker': ["Russia","China"], link: 'https://hrf.org/events_talks/voices-from-the-internet-underground/' },
  { 'undefined': ["South Korea","China","North Korea"], link: 'https://hrf.org/events_talks/hacking-north-koreas-information-monopoly/' },
  { 'Václav Havel': [], link: 'https://hrf.org/events_talks/look-away/' },
  { 'undefined': ["South Korea","China","North Korea"], link: 'https://hrf.org/events_talks/a-north-korean-rescue-story/' },
  { 'undefined': [], link: 'https://hrf.org/events_talks/everywhere-i-go-live-in-oslo-with-the-norwegian-girls-choir/' },
  { 'undefined': ["Russia"], link: 'https://hrf.org/events_talks/banks-not-tanks/' },
  { 'The Honey Trees': [], link: 'https://hrf.org/events_talks/to-be-with-you-and-nightingale-live-in-oslo/' },
  { 'The Honey Trees': [], link: 'https://hrf.org/events_talks/ammons-horn-wake-the-earth/' },
  { 'Wonho Chung': [], link: 'https://hrf.org/events_talks/live-from-the-oslo-freedom-forum/' },
  { 'Andrés Velasco': ["Chile"], link: 'https://hrf.org/events_talks/ending-dictatorship-and-building-democracy-with-a-pencil/' },
  { 'Steven Pinker': [], link: 'https://hrf.org/events_talks/the-better-angels-of-our-nature/' },
  { 'Marcela Turati Muñoz': ["Mexico"], link: 'https://hrf.org/events_talks/the-price-of-mexicos-drug-war/' },
  { 'undefined': ["Ukraine","Russia"], link: 'https://hrf.org/events_talks/i-am-a-ukrainian/' },
  { 'Jeffrey Wright': ["Sierra Leone"], link: 'https://hrf.org/events_talks/mining-in-africa-for-the-21st-century/' },
  { 'Jon Callas': [], link: 'https://hrf.org/events_talks/the-revolution-will-be-encrypted/' },
  { 'Ti-Anna Wang': ["China"], link: 'https://hrf.org/events_talks/fighting-for-my-fathers-freedom/' },
  { 'CJ Adams': [], link: 'https://hrf.org/events_talks/shielding-free-speech-online/' },
  { 'Anwar Ibrahim': ["Malaysia"], link: 'https://hrf.org/events_talks/malaysias-most-wanted/' },
  { 'Mac-Jordan Degadjor': ["Ghana","Jordan"], link: 'https://hrf.org/events_talks/africas-tech-frontier/' },
  { 'undefined': ["Sri Lanka"], link: 'https://hrf.org/events_talks/sri-lankas-deadly-profession/' },
  { 'Bassem Youssef': ["Egypt"], link: 'https://hrf.org/events_talks/2014-keynote-address/' },
  { 'undefined': ["Cuba"], link: 'https://hrf.org/events_talks/cubas-underground-revolution/' },
  { 'Pussy Riot': ["Russia"], link: 'https://hrf.org/events_talks/a-conversation-with-pussy-riot/' },
  { 'Nico Sell': [], link: 'https://hrf.org/events_talks/escape-the-internet/' },
  { 'Ian Birrell': ["Ukraine","Egypt","Azerbaijan"], link: 'https://hrf.org/events_talks/sticks-stones-and-broken-bones/' },
  { 'Yeonmi Park': ["North Korea"], link: 'https://hrf.org/events_talks/north-koreas-black-market-generation/' },
  { 'Iyad el-Baghdadi': [], link: 'https://hrf.org/events_talks/the-arab-spring-manifesto/' },
  { 'undefined': ["Jordan"], link: 'https://hrf.org/events_talks/superheroes-against-extremism/' },
  { 'undefined': ["Russia"], link: 'https://hrf.org/events_talks/for-your-and-our-freedom-1968-2014/' },
  { 'Erdem Gunduz': [], link: 'https://hrf.org/events_talks/the-standing-man/' },
  { 'Greg Mortenson': ["Pakistan","Afghanistan"], link: 'https://hrf.org/events_talks/stones-into-schools/' },
  { 'Akhmed Zakayev': ["Russia"], link: 'https://hrf.org/events_talks/chechnyas-leader-in-exile/' },
  { 'Harry Wu': ["China"], link: 'https://hrf.org/events_talks/laogai-the-chinese-gulag/' },
  { 'Elie Wiesel': ["Rwanda","Cambodia"], link: 'https://hrf.org/events_talks/unmasking-evil/' },
  { 'Vo Van Ai': ["Vietnam"], link: 'https://hrf.org/events_talks/the-impact-of-indifference/' },
  { 'Mutabar Tadjibaeva': ["Uzbekistan"], link: 'https://hrf.org/events_talks/the-fiery-heart-of-uzbekistan/' },
  { 'Hans Rosling': [], link: 'https://hrf.org/events_talks/the-statistics-of-human-rights/' },
  { 'Park Sang Hak': ["North Korea"], link: 'https://hrf.org/events_talks/north-koreas-freedom-fighters/' },
  { 'Jacqueline Moudeina': ["Chad"], link: 'https://hrf.org/events_talks/seeking-justice-in-chad/' },
  { 'Vytautas Landsbergis': ["Lithuania"], link: 'https://hrf.org/events_talks/human-rights-and-political-leadership/' },
  { 'Victor Hugo Cárdenas': ["Bolivia"], link: 'https://hrf.org/events_talks/the-erosion-of-democracy-in-bolivia/' },
  { 'Jung Chang': ["China"], link: 'https://hrf.org/events_talks/the-historical-truth-behind-maos-china/' },
  { 'Craig Johnstone': [], link: 'https://hrf.org/events_talks/refugees-and-human-rights/' },
  { 'Jack Healey': [], link: 'https://hrf.org/events_talks/re-energizing-human-rights/' },
  { 'Václav Havel': ["Czech Republic"], link: 'https://hrf.org/events_talks/the-responsibility-of-a-free-society/' },
  { 'Palden Gyatso': ["China"], link: 'https://hrf.org/events_talks/fire-under-the-snow/' },
  { 'undefined': ["Mauritania"], link: 'https://hrf.org/events_talks/ending-slavery-in-mauritania/' },
  { 'Emil Constantinescu': ["Romania"], link: 'https://hrf.org/events_talks/pedagogy-of-suffering/' },
  { 'Leyla Zana': ["Turkey"], link: 'https://hrf.org/events_talks/the-struggle-of-turkeys-kurds/' },
  { 'Vladimir Bukovsky': [], link: 'https://hrf.org/events_talks/my-life-as-a-dissenter/' },
  { 'Ladan Boroumand': ["Iran"], link: 'https://hrf.org/events_talks/omid-an-iranian-memorial/' },
  { 'Elena Bonner': ["Israel","Russia"], link: 'https://hrf.org/events_talks/internal-exile-in-the-soviet-union/' },
  { 'Ales Bialiatski': ["Belarus"], link: 'https://hrf.org/events_talks/exposing-tyranny-in-belarus/' },
  { 'Jimmy Wales': ["Iran"], link: 'https://hrf.org/events_talks/wikipedia-and-exposing-the-truth/' },
  { 'Hernando de Soto': ["Peru"], link: 'https://hrf.org/events_talks/saving-the-worlds-poor/' },
  { 'undefined': ["Cuba"], link: 'https://hrf.org/events_talks/opening-a-window-into-cuba/' },
  { 'Thich Quang Do': ["Vietnam"], link: 'https://hrf.org/events_talks/forbidden-faith-in-vietnam/' },
  { 'Zuhdi Jasser': [], link: 'https://hrf.org/events_talks/how-islam-works-with-democracy/' },
  { 'Sophal Ear': ["Cambodia"], link: 'https://hrf.org/events_talks/beneath-the-killing-fields-of-cambodia/' },
  { 'Sima Samar': ["Afghanistan"], link: 'https://hrf.org/events_talks/rebuilding-afghanistan/' },
  { 'Siegmar Faust': ["Germany"], link: 'https://hrf.org/events_talks/exposing-a-nation-of-spies/' },
  { 'Samuel Kofi Woods': ["Liberia"], link: 'https://hrf.org/events_talks/in-the-shadow-of-liberias-civil-war/' },
  { 'Rebiya Kadeer': [], link: 'https://hrf.org/events_talks/the-birth-of-a-thousand-mothers/' },
  { 'Pierre Claver Mbonimpa': ["Burundi"], link: 'https://hrf.org/events_talks/reform-in-burundi/' },
  { 'undefined': [], link: 'https://hrf.org/events_talks/three-dimensions-of-transparency/' },
  { 'Mukhtar Mai': ["Pakistan"], link: 'https://hrf.org/events_talks/women-against-honor-punishment/' },
  { 'Mart Laar': ["Estonia"], link: 'https://hrf.org/events_talks/the-singing-revolution/' },
  { 'Marina Nemat': ["Iran"], link: 'https://hrf.org/events_talks/escaping-irans-dungeons/' },
  { 'Marcel Granier': ["Venezuela"], link: 'https://hrf.org/events_talks/the-assault-on-venezuelas-free-press/' },
  { 'Lubna al-Hussein': ["Sudan"], link: 'https://hrf.org/events_talks/unbinding-the-women-of-sudan/' },
  { 'Lidia Yusupova': [], link: 'https://hrf.org/events_talks/chechnyas-witness/' },
  { 'Leopoldo López': ["Colombia","Venezuela"], link: 'https://hrf.org/events_talks/all-rights-for-all-people/' },
  { 'Lech Walesa': [], link: 'https://hrf.org/events_talks/solidarity/' },
  { 'undefined': ["Uganda"], link: 'https://hrf.org/events_talks/ugandas-nuremberg-laws/' },
  { 'Kang Chol-hwan': ["South Korea","North Korea"], link: 'https://hrf.org/events_talks/ten-years-in-north-koreas-gulags/' },
  { 'Julian Assange': ["Australia"], link: 'https://hrf.org/events_talks/the-whistleblower/' },
  { 'Guadalupe Llori': ["Ecuador"], link: 'https://hrf.org/events_talks/elected-in-ecuador-imprisoned-for-dissent/' },
  { 'Gilbert Tuhabonye': ["Burundi"], link: 'https://hrf.org/events_talks/outrunning-genocide/' },
  { 'undefined': ["Russia"], link: 'https://hrf.org/events_talks/chess-human-rights-and-the-self/' },
  { 'Diego Arria': ["Serbia","Venezuela","Kuwait"], link: 'https://hrf.org/events_talks/the-greatest-coverup-in-u-n-history/' },
  { 'Claudia Rosett': [], link: 'https://hrf.org/events_talks/watching-the-watchmen/' },
  { 'Clara Rojas': ["Colombia"], link: 'https://hrf.org/events_talks/2234-days-with-the-farc/' },
  { 'Benjamin Skinner': [], link: 'https://hrf.org/events_talks/a-modern-day-abolitionist/' },
  { 'undefined': [], link: 'https://hrf.org/events_talks/against-all-hope/' },
  { 'Anwar Ibrahim': ["Malaysia"], link: 'https://hrf.org/events_talks/confronting-half-a-century-of-one-party-rule/' },
  { 'Alyaksandr Kazulin': ["Belarus"], link: 'https://hrf.org/events_talks/challenging-europes-last-dictator/' },
  { 'undefined': ["Yemen"], link: 'https://hrf.org/events_talks/yemens-assault-on-media/' },
  { 'Wael Ghonim': ["Egypt"], link: 'https://hrf.org/events_talks/the-future-of-egypt/' },
  { 'undefined': ["Tunisia"], link: 'https://hrf.org/events_talks/tunisias-unfinished-revolution/' },
  { 'undefined': ["Bahrain","Iran"], link: 'https://hrf.org/events_talks/heroes-of-bahrains-revolution/' },
  { 'Yang Jianli': ["China"], link: 'https://hrf.org/events_talks/the-myth-of-han-china/' },
  { 'undefined': ["Sudan"], link: 'https://hrf.org/events_talks/the-lessons-of-sudans-past/' },
  { 'Zoya Phan': [], link: 'https://hrf.org/events_talks/a-story-of-life-and-death/' },
  { 'Zoya Phan': [], link: 'https://hrf.org/events_talks/unmasking-burmas-junta/' },
  { 'Zhanna Litvina': ["Belarus"], link: 'https://hrf.org/events_talks/lukashenkos-iron-grip/' },
  { 'Wan Yanhai': ["China"], link: 'https://hrf.org/events_talks/exposing-chinas-aids-crisis/' },
  { 'Violet Banda': ["Malawi"], link: 'https://hrf.org/events_talks/giving-voice-to-malawis-youth/' },
  { 'Vincent Manoharan': ["India"], link: 'https://hrf.org/events_talks/the-untouchables-of-india/' },
  { 'undefined': ["Argentina"], link: 'https://hrf.org/events_talks/terrorism-and-impunity-in-argentina/' },
  { 'undefined': [], link: 'https://hrf.org/events_talks/supply-chain-slavery/' },
  { 'undefined': ["Saudi Arabia"], link: 'https://hrf.org/events_talks/royal-rules-in-saudi-arabia/' },
  { 'undefined': ["Democratic Republic of the Congo","Somalia","Sudan","South Sudan"], link: 'https://hrf.org/events_talks/the-art-of-activism/' },
  { 'undefined': [], link: 'https://hrf.org/events_talks/the-human-cost-of-the-war-on-drugs/' },
  { 'undefined': ["Zimbabwe"], link: 'https://hrf.org/events_talks/in-mugabes-crosshairs/' },
  { 'undefined': ["Syria"], link: 'https://hrf.org/events_talks/syria-no-turning-back/' },
  { 'undefined': ["Cambodia"], link: 'https://hrf.org/events_talks/survivors-journey/' },
  { 'undefined': [], link: 'https://hrf.org/events_talks/consent-of-the-networked/' },
  { 'undefined': ["Pakistan"], link: 'https://hrf.org/events_talks/building-a-free-pakistan/' },
  { 'undefined': ["Ethiopia"], link: 'https://hrf.org/events_talks/outmaneuvering-state-control/' },
  { 'undefined': ["South Africa"], link: 'https://hrf.org/events_talks/inside-the-global-arms-trade/' },
  { 'undefined': ["South Africa"], link: 'https://hrf.org/events_talks/freedoms-counsel/' },
  { 'Nick Cohen': [], link: 'https://hrf.org/events_talks/censorship-in-an-age-of-freedom/' },
  { 'Chee Soon Juan': ["Singapore"], link: 'https://hrf.org/events_talks/the-secret-of-singapore/' },
  { 'undefined': ["Nepal"], link: 'https://hrf.org/events_talks/freeing-the-daughters-of-nepal/' },
  { 'undefined': [], link: 'https://hrf.org/events_talks/googles-think-do-tank/' },
  { 'undefined': ["Haiti"], link: 'https://hrf.org/events_talks/haitis-human-property/' },
  { 'undefined': ["Russia"], link: 'https://hrf.org/events_talks/organizing-the-opposition/' },
  { 'undefined': ["Guinea","Equatorial Guinea"], link: 'https://hrf.org/events_talks/in-the-kingdom-of-obiang/' },
  { 'undefined': ["Russia"], link: 'https://hrf.org/events_talks/in-putins-shadow/' },
  { 'Soraya Bahgat': ["Ghana","Egypt"], link: 'https://hrf.org/events_talks/women-under-threat/' },
  { 'Donald Boudreaux': ["Angola","Singapore"], link: 'https://hrf.org/events_talks/facade-capitalism-and-its-threat-to-human-rights/' },
  { 'Maryam Nayeb Yazdi': ["Iran"], link: 'https://hrf.org/events_talks/irans-weapon-of-choice/' },
  { 'Sasa Vucinic': ["Serbia","Russia"], link: 'https://hrf.org/events_talks/investing-in-free-press/' },
  { 'Mario Vargas Llosa': ["Peru"], link: 'https://hrf.org/events_talks/literature-freedom-and-power/' },
  { 'Ambiga Sreenevasan': ["Malaysia"], link: 'https://hrf.org/events_talks/unrigging-an-election/' },
  { 'Hannah Song': ["North Korea"], link: 'https://hrf.org/events_talks/north-koreas-rising-civil-society/' },
  { 'undefined': [], link: 'https://hrf.org/events_talks/too-young-to-wed/' },
  { 'Lobsang Sangay': ["China"], link: 'https://hrf.org/events_talks/democracy-in-exile/' },
  { 'Srdja Popovic': ["Serbia"], link: 'https://hrf.org/events_talks/revolution-101/' },
  { 'Jenan Moussa': ["Syria"], link: 'https://hrf.org/events_talks/syrias-uncovered-story/' },
  { 'undefined': ["Liberia","Central African Republic"], link: 'https://hrf.org/events_talks/rule-of-law-for-sale/' },
  { 'George Ayittey': ["Ghana"], link: 'https://hrf.org/events_talks/a-tyrants-best-friend/' },
  { 'Thomas Glave': ["Jamaica"], link: 'https://hrf.org/events_talks/ending-anti-gay-violence-in-jamaica/' },
  { 'undefined': [], link: 'https://hrf.org/events_talks/competitive-authoritarianism/' },
  { 'Shirin Ebadi': ["Iran"], link: 'https://hrf.org/events_talks/irans-awakening/' },
  { 'Philippe Douste-Blazy': [], link: 'https://hrf.org/events_talks/innovative-financing-for-development/' },
  { 'Mona Eltahawy': ["Egypt"], link: 'https://hrf.org/events_talks/egypts-revolutionary-censors/' },
  { 'Malahat Nasibova': ["Azerbaijan"], link: 'https://hrf.org/events_talks/azerbaijans-secrets/' },
  { 'Leymah Gbowee': ["Liberia"], link: 'https://hrf.org/events_talks/pray-the-devil-back-to-hell/' },
  { 'John Ralston Saul': [], link: 'https://hrf.org/events_talks/censorship-for-sale/' },
  { 'Jody Williams': [], link: 'https://hrf.org/events_talks/the-power-of-one/' },
  { 'Gregory Shvedov': ["Russia"], link: 'https://hrf.org/events_talks/the-caucasian-knot/' },
  { 'Fernão Lara Mesquita': ["Brazil","China"], link: 'https://hrf.org/events_talks/repression-in-brazil-past-and-present/' },
  { 'Emil Constantinescu': ["Romania"], link: 'https://hrf.org/events_talks/soft-power-and-global-peace/' },
  { 'Busi Kheswa': ["South Africa"], link: 'https://hrf.org/events_talks/stain-on-the-rainbow-nation/' },
  { 'Belisario Betancur': ["Colombia"], link: 'https://hrf.org/events_talks/negotiating-peace/' },
  { 'Nada Dhaif': ["Bahrain"], link: 'https://hrf.org/events_talks/treating-the-invisible-wounds-of-torture/' },
  { 'Mona Eltahawy': ["Brazil","Egypt","Russia"], link: 'https://hrf.org/events_talks/evolution-of-censorship/' },
  { 'Wael Ghonim': ["Tunisia","Bahrain","Egypt","Libya","Syria","Sudan"], link: 'https://hrf.org/events_talks/dawn-of-a-new-arab-world/' },
  { 'Uki Goñi': ["Argentina"], link: 'https://hrf.org/events_talks/argentinas-desaparecidos/' },
  { 'Zoya Phan': ["Ghana"], link: 'https://hrf.org/events_talks/the-aid-debate/' },
  { 'Alejandro Toledo': ["Peru"], link: 'https://hrf.org/events_talks/elected-autocrats/' },
  { 'Barbara Demick': ["North Korea"], link: 'https://hrf.org/events_talks/everday-lives-in-north-korea/' },
  { 'Pussy Riot': ["Russia"], link: 'https://hrf.org/events_talks/mobilizing-with-art/' },
  { 'undefined': ["Kosovo"], link: 'https://hrf.org/events_talks/on-air-and-under-attack-in-kosovo/' },
  { 'undefined': ["Indonesia"], link: 'https://hrf.org/events_talks/indonesias-hidden-colony/' },
  { 'undefined': ["Moldova","Nepal","Cuba","China","Laos","North Korea","Vietnam"], link: 'https://hrf.org/events_talks/behind-communisms-curtain/' },
  { 'undefined': ["Kazakhstan"], link: 'https://hrf.org/events_talks/kazakhstans-great-facade/' },
  { 'undefined': ["Saudi Arabia"], link: 'https://hrf.org/events_talks/the-drive-for-freedom/' },
  { 'undefined': ["Ecuador"], link: 'https://hrf.org/events_talks/rethinking-poverty/' },
  { 'undefined': ["Venezuela"], link: 'https://hrf.org/events_talks/condemned-to-venezuelas-prisons/' },
  { 'undefined': ["Ecuador"], link: 'https://hrf.org/events_talks/the-42-million-op-ed/' },
  { 'undefined': ["Russia"], link: 'https://hrf.org/events_talks/protesting-for-democracy/' },
  { 'Owen Maseko': ["Zimbabwe"], link: 'https://hrf.org/events_talks/painting-a-massacre/' },
  { 'undefined': ["Angola"], link: 'https://hrf.org/events_talks/growing-wealth-shrinking-democracy/' },
  { 'Lapiro de Mbanga': ["Cameroon"], link: 'https://hrf.org/events_talks/singing-truth-to-power/' },
  { 'Justin Kosslyn': [], link: 'https://hrf.org/events_talks/mapping-human-trafficking/' },
  { 'undefined': ["Libya"], link: 'https://hrf.org/events_talks/devils-advocates/' },
  { 'Natalia Kaliada': ["Belarus"], link: 'https://hrf.org/events_talks/theatre-of-resistance/' },
  { 'Afua Hirsch': ["Ghana","Mali"], link: 'https://hrf.org/events_talks/malis-islamist-takeover/' },
  { 'Luke Harding': ["Russia"], link: 'https://hrf.org/events_talks/putins-mafia-state/' },
  { 'Roberto de Jesús Guerra Pérez': ["Cuba"], link: 'https://hrf.org/events_talks/reporting-from-an-island-prison/' },
  { 'Peter Godwin': ["Zimbabwe"], link: 'https://hrf.org/events_talks/mugabes-reign-of-terror/' },
  { 'Asmaa al-Ghoul': ["Israel","Palestine"], link: 'https://hrf.org/events_talks/exposing-hamass-rule/' },
  { 'Ali Ferzat': ["Syria"], link: 'https://hrf.org/events_talks/the-strength-of-satire/' },
  { 'Meron Estefanos': ["Ethiopia","Eritrea"], link: 'https://hrf.org/events_talks/no-escape-from-eritrea/' },
  { 'undefined': [], link: 'https://hrf.org/events_talks/a-different-kind-of-warfare/' },
  { 'Chen Guangcheng': ["China"], link: 'https://hrf.org/events_talks/chinas-inevitable-transformation/' },
  { 'Chee Soon Juan': ["Singapore"], link: 'https://hrf.org/events_talks/economic-sustainability-in-authoritarian-systems/' },
  { 'undefined': ["Russia"], link: 'https://hrf.org/events_talks/avenging-magnitskys-murder/' },
  { 'Donald Boudreaux': [], link: 'https://hrf.org/events_talks/the-case-for-economic-freedom/' },
  { 'undefined': ["Bahrain"], link: 'https://hrf.org/events_talks/breaking-free-of-bahrains-regime/' },
  { 'undefined': ["Afghanistan"], link: 'https://hrf.org/events_talks/transforming-media-transforming-women/' },
  { 'Soraya Bahgat': ["Egypt"], link: 'https://hrf.org/events_talks/the-voice-of-women-is-a-revolution/' },
  { 'Arzina Begum': ["Bangladesh"], link: 'https://hrf.org/events_talks/abolishing-child-marriage/' },
  { 'Julio Borges': ["Venezuela"], link: 'https://hrf.org/events_talks/the-democratic-rebellion/' },
];
