const names = [
  'Fartuun Adan',
  'Mai Khoi',
  'Aayat Alqormozi',
  'Myeong Seong-hee',
  'Ji Seong-ho',
  'Clare Rewcastle Brown',
  'Bill Tai',
  'Mariana Dahan',
  'Vanessa Tsehaye',
  'Mu Sochua',
  'Megha Rajagopalan',
  'Vladimir  Kara-Murza',
  'Omar Sharif Jr.',
  'Joanna Hausmann',
  'Fang Zheng',
  'Rick Doblin',
  '​Farida Nabourema',
  'Fatemah Qaderyan',
  'Mai Khoi',
  'Emmanuel Jal',
  'Ian C. Kelly',
  'Yeonmi Park',
  'Manal  al-Sharif',
  'Arthur Breitman',
  'Natalia Kaliada',
  'Tiff Stevenson',
  'Fred Bauma',
  '​Svitlana Zalishchuk',
  'Ine Eriksen Søreide',
  'Rick Doblin',
  'Mai Khoi',
  'Meron Estefanos',
  'Mu Sochua',
  'Ryan Shea',
  'Galia Benartzi',
  'Arthur Breitman',
  'Jason Silva',
  'Wael Ghonim',
  'Jerry Sesanga',
  'Nasako Besingi',
  'Jose Luis Martin Chito Gascon',
  'Vanessa Tsehaye',
  'Asma Khalifa',
  'Maziar Bahari',
  '​Edipcia Dubón',
  'Fang Zheng',
  'Lebo Mashile',
  'Clare Rewcastle Brown',
  '​Netiwit Chotiphatphaisal',
  '​Farida Nabourema',
  'Fatemah Qaderyan',
  'Megha Rajagopalan',
  '​Belquis Al Lahabi',
  'Evan Mawarire',
  'Omar Sharif Jr.',
  'Memory Banda',
  'Anastasia Lin',
  'Rafael Marques De Morais',
  'Iyad el-Baghdadi',
  'Zineb El Rhazoui',
  'Vladimir  Kara-Murza',
  'Elif Shafak',
  'Ji Seong-ho',
  'Srdja Popovic',
  'Marina Nemat',
  'Wuilly Arteaga',
  '​Abdulrahman Al-Mawwas',
  'Chris Turner',
  'Anas Aremeyaw Anas',
  'Aayat Alqormozi',
  'Silvanos Mudzvova',
  'Memory Banda',
  'Joe Lonsdale',
  'Wai Wai Nu',
  'Carah Faye',
  'Grace Jo',
  'Raed Fares',
  'Antonietta Ledezma',
  'Erna Solberg',
  'Ahmedur Rashid Chowdhury',
  'Mohamed Nasheed',
  'Xavier "Bonil" Bonilla',
  'Anne Applebaum',
  'Elif Shafak',
  'Vian Dakhil',
  'Firuzeh Mahmoudi',
  'Luis Almagro',
  'Evan Mawarire',
  'Thulani Maseko',
  'Denis Mukwege',
  'Aminatou Haidar',
  'Emin Milli',
  'Anastasia Lin',
  'Danilo "El Sexto" Maldonado',
  'Wole Soyinka',
  'Vivek Maru',
  'Lisa Sánchez',
  'Maajid Nawaz',
  'Shui-Meng Ng',
  'Roya Mahboob',
  'Jimmy Wales',
  'Rachana Sunar',
  'Anjan Sundaram',
  'Bjørn Ihler',
  'Viktor Yushchenko',
  'Gustavo Coronel',
  'Tom Burgis',
  'Bill  Browder',
  'Vladimir  Kara-Murza',
  'Nabeel Rajab',
  'Abdellah  Taia',
  'Marc Ona Essangui',
  'Kambiz Hosseini',
  'Larry Diamond',
  'Amira  Yahyaoui',
  'Børge Brende',
  'Kimberley Motley',
  'Pravit Rojanaphruk',
  'Mustafa Akyol',
  'Alaa Murabit',
  'Kenan Malik',
  'Shiraz Maher',
  'Rayma Suprani',
  'Colin Crowell',
  'Maryam Faghihimani',
  'Ji Seong-ho',
  'Zineb El Rhazoui',
  'Saad Mohseni',
  'Tanele Maseko',
  'Nico Sell',
  'Ian Birrell',
  'Omar Sharif Jr.',
  'Jamila Raqib',
  'Abdalaziz Alhamza',
  'Michael  Anti',
  'Janet Hinostroza',
  'Rosa María Payá',
  'Fatou Jaw Manneh',
  'Shorna Shahida Akter',
  'Flemming Rose',
  'Emily Parker',
  'Park Sang Hak',
  'Hyeonseo  Lee',
  'Garry  Kasparov',
  'The Honey Trees',
  'Wonho Chung',
  'Andrés Velasco',
  'Steven Pinker',
  'Marcela Turati Muñoz',
  'Jeffrey Wright',
  'Jon Callas',
  'Ti-Anna Wang',
  'CJ Adams',
  'Nurul Izzah Anwar',
  'Mac-Jordan Degadjor',
  'Frederica  Jansz',
  'Bassem Youssef',
  'Yoani  Sánchez',
  'Pussy Riot',
  'Nico Sell',
  'Ian Birrell',
  'Yeonmi Park',
  'Iyad el-Baghdadi',
  'Suleiman  Bakhit',
  'Mikhail  Khodorkovsky',
  'Erdem Gunduz',
  'Greg Mortenson',
  'Akhmed Zakayev',
  'Harry Wu',
  'Elie Wiesel',
  'Vo Van Ai',
  'Mutabar Tadjibaeva',
  'Hans Rosling',
  'Park Sang Hak',
  'Jacqueline Moudeina',
  'Vytautas Landsbergis',
  'Victor Hugo Cárdenas',
  'Jung Chang',
  'Craig Johnstone',
  'Jack Healey',
  'Václav Havel',
  'Palden Gyatso',
  'Abdel Nasser Ould Ethmane',
  'Emil Constantinescu',
  'Leyla Zana',
  'Vladimir Bukovsky',
  'Ladan Boroumand',
  'Elena Bonner',
  'Ales Bialiatski',
  'Jimmy Wales',
  'Hernando de Soto',
  'Yoani  Sánchez',
  'Thich Quang Do',
  'Zuhdi Jasser',
  'Sophal Ear',
  'Sima Samar',
  'Siegmar Faust',
  'Samuel Kofi Woods',
  'Rebiya Kadeer',
  'Pierre Claver Mbonimpa',
  'Mukhtar Mai',
  'Mart Laar',
  'Marina Nemat',
  'Marcel Granier',
  'Lubna al-Hussein',
  'Lidia Yusupova',
  'Leopoldo López',
  'Lech Walesa',
  'Kasha Jacqueline (Nabagesera)',
  'Kang Chol-hwan',
  'Julian Assange',
  'Guadalupe Llori',
  'Gilbert Tuhabonye',
  'Garry  Kasparov',
  'Diego Arria',
  'Claudia Rosett',
  'Clara Rojas',
  'Benjamin Skinner',
  'Armando Valladares',
  'Anwar Ibrahim',
  'Alyaksandr Kazulin',
  'Abdulkarim Al-Khaiwani',
  'Wael Ghonim',
  'Lina  Ben Mhenni',
  'Maryam  al-Khawaja',
  'Yang Jianli',
  'Amir Ahmad  Nasr',
  'Zoya Phan',
  'Zhanna Litvina',
  'Wan Yanhai',
  'Violet Banda',
  'Vincent Manoharan',
  'Victoria Villarruel',
  'George Ayittey',
  'Thomas Glave',
  'Shirin Ebadi',
  'Philippe Douste-Blazy',
  'Mona Eltahawy',
  'Malahat Nasibova',
  'Leymah Gbowee',
  'John Ralston Saul',
  'Jody Williams',
  'Gregory Shvedov',
  'Fernão Lara Mesquita',
  'Emil Constantinescu',
  'Busi Kheswa',
  'Belisario Betancur',
  'Nada Dhaif',
  'Mona Eltahawy',
  'Maryam  al-Khawaja',
  'Uki Goñi',
  'Zoya Phan',
  'Alejandro Toledo',
  'Barbara Demick',
  'Pyotr  Verzilov',
  'Jeta  Xharra',
  'Benny  Wenda',
  'Tomas  van Houtryve',
  'Alexey  Tikhonov',
  'Manal  al-Sharif',
  'Mauricio  Rodas',
  'Humberto  Prado',
  'Natalia  Pelevine',
  'Julia  Ormond',
  'Naomi  Natale',
  'Ethan  Nadelmann',
  'Jestina  Mukoko',
  'Ausama  Monajed',
  'Somaly  Mam',
  'Rebecca  MacKinnon',
  'Asma  Jahangir',
  'Abebe  Gellaw',
  'Andrew  Feinstein',
  'Irwin  Cotler',
  'Nick Cohen',
  'Chee Soon Juan',
  'Urmila  Chaudhary',
  'Scott  Carpenter',
  'Jean-Robert  Cadet',
  'Denis  Bilunov',
  'Tutu  Alicante',
  'Pyotr  Verzilov',
  'Soraya Bahgat',
  'Rafael Marques De Morais',
  'Maryam Nayeb Yazdi',
  'Sasa Vucinic',
  'Mario Vargas Llosa',
  'Ambiga Sreenevasan',
  'Hannah Song',
  'Lobsang Sangay',
  'Srdja Popovic',
  'Jenan Moussa',
  'Owen Maseko',
  'Rafael Marques De Morais',
  'Lapiro de Mbanga',
  'Justin Kosslyn',
  'Natalia Kaliada',
  'Luke Harding',
  'Roberto de Jesús  Guerra Pérez',
  'Peter Godwin',
  'Asmaa al-Ghoul',
  'Ali Ferzat',
  'Meron Estefanos',
  'Chen Guangcheng',
  'Chee Soon Juan',
  'Bill  Browder',
  'Donald Boudreaux',
  'Ali  Abdulemam',
  'Shakeela  Abrahimkhil',
  'Soraya Bahgat',
  'Arzina Begum',
  'Julio Borges',
];


const countries = [
    'Antigua and Barbuda', 'Argentina', 'Bahamas', 'Barbados', 'Belize', 'Brazil', 'Canada', 'Chile', 'Colombia', 'Costa Rica', 'Dominica', 'Dominican Republic', 'El Salvador', 'Haiti', 'French Guiana', 'Grenada', 'Guatemala', 'Guyana',
    'Jamaica', 'Mexico', 'Panama', 'Paraguay', 'Peru', 'Puerto Rico', 'St. Kitts and Nevis', 'St. Lucia', 'St. Vincent and Grenadines', 'Suriname', 'Trinidad and Tobago', 'United States of America', 'Uruguay', 'Israel', 'Lebanon', 'Ukraine', 'Georgia', 'Benin', 'Botswana',
    'Cape Verde', 'Ghana', 'Lesotho', 'Liberia', 'Mali', 'Mauritius', 'Namibia', 'Senegal', 'Sao Tome and Principe', 'South Africa', 'Australia', 'Bhutan', 'East Timor (or Timor-Leste)', 'India', 'Indonesia', 'Japan', 'Kiribati', 'Marshall Islands', 'Micronesia', 'Mongolia',
    'Nauru', 'New Zealand', 'Palau', 'Papua New Guinea', 'Samoa', 'Solomon Islands', 'South Korea', 'Republic of Korea', 'Taiwan', 'Tonga', 'Tuvalu', 'Vanuatu', 'Albania', 'Andorra', 'Austria', 'Belgium', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia',
    'Czech Republic', 'Cyprus', 'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Iceland', 'Ireland', 'Italy', 'Latvia', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Malta', 'Macedonia', 'Monaco', 'Netherlands',
    'Norway', 'Poland', 'Portugal', 'Romania', 'San Marino', 'Serbia', 'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland', 'United Kingdom', 'Greenland',
    'Bolivia', 'Nicaragua', 'Ecuador', 'Honduras', 'Tunisia', 'Armenia', 'Kyrgyzstan', 'Moldova', 'Burkina Faso', 'Central African Republic', 'Comoros', 'Côte D’Ivoire', 'Côte d\'Ivoire', 'Gambia', 'Guinea', 'Guinea-Bissau', 'Kenya', 'Madagascar', 'Malawi',
    'Mauritania', 'Mozambique', 'Niger', 'Nigeria', 'Seychelles', 'Sierra Leone', 'Tanzania', 'Togo', 'Zambia', 'Zanzibar', 'Bangladesh', 'Fiji', 'Malaysia', 'Maldives', 'Myanmar/Burma', 'Nepal', 'Pakistan', 'Sri Lanka', 'Hong Kong', 'Philippines', 'Macau', 'Hungary', 'Kosovo', 'Montenegro',
    'Cuba', 'Venezuela', 'Algeria', 'Bahrain', 'Egypt', 'Iran', 'Iraq', 'Jordan', 'Kuwait', 'Libya', 'Morocco', 'Oman', 'Palestine', 'Qatar', 'Saudi Arabia',
    'Turkey', 'Syria', 'United Arab Emirates', 'Western Sahara', 'Yemen', 'Azerbaijan', 'Belarus', 'Kazakhstan', 'Russia', 'Tajikistan', 'Turkmenistan', 'Uzbekistan', 'Angola', 'Burundi', 'Cameroon', 'Chad',
    'Democratic Republic of Congo-(Kinshasa)', 'Democratic Republic of the Congo', 'Djibouti', 'Equatorial Guinea', 'Ethiopia', 'Eritrea', 'Eswatini (Swaziland)', 'Gabon', 'Republic of Congo (Brazzaville)', 'Rwanda', 'Somalia', 'Sudan', 'South Sudan', 'Uganda', 'Zimbabwe', 'Afghanistan', 'Brunei', 'Cambodia',
    'China', 'Laos', 'Lao PDR', 'North Korea', 'Dem. Rep. Korea', 'Singapore', 'Thailand', 'Vietnam',
];

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

function printNames() {
	for (var i = 0; i < document.getElementsByClassName('Item-Medium-Text').length; i++) {
	if (document.getElementsByClassName('Item-Medium-Text')[i]) {
			console.log(document.getElementsByClassName('Item-Medium-Text')[i].innerHTML)
		}
	}
}

async function printCountriesByLink() {
	const talkSections = document.getElementsByClassName('Talkssection');
	for (var i = 0; i < talkSections.length; i++) {
		const t = talkSections[i];
		const children = t.children;
		for (var j = 0; j < children.length; j++) {
			await  sleep(500);
			const child = children[j];
			const link = child.href;
			const data = await $.get(link);
			const arr = [];
			let name;
			for (var k = 0; k < names.length; k++) {
				if (data.includes(names[k])) {
					name = names[k]
				}
			}

			for (var k = 0; k < countries.length; k++) {
				if (data.includes(countries[k])) {
					arr.push(countries[k]);
				}
			}
			console.log(`{ ${name}: ${JSON.stringify(arr)}, link: ${link} }`);
		}
	}
}